### ISSUE TITLE
[Low Priority] ERR_HTTP_HEADERS_SENT warning

### ISSUE THREAD

**Issue by egormesyats** [storefront-foundation/magento2-connector#13]
Response object of NextJS shows this error when we're setting multiple "set-cookie" headers, which is required by the logic of session handling. I'm still not clear how to fix this issue. I played with different suggestions from here: https://stackoverflow.com/questions/52122272/err-http-headers-sent-cannot-set-headers-after-they-are-sent-to-the-client, but it wasn't helpful in our case. So probably it's something nextjs specific.

Ref: https://moovweb.atlassian.net/browse/PTR-14

**Comment by dijs** [comment]
@egormesyats Please try upgrading to the latest version of XDN and retesting. I was seeing the same issue for the salesforce connector, but after upgrading, I am not seeing this error anymore.
